sudo: required
services:
  - docker

before_install:
  - docker build -t manalikekre/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true manalikekre/react-test npm run test

after_success:
  - docker build -t manalikekre/multi-client ./client
  - docker build -t manalikekre/multi-nginx ./nginx
  - docker build -t manalikekre/multi-server ./server
  - docker build -t manalikekre/multi-worker ./worker
  #log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login --u "$DOCKER_ID" --password-stdin
  #Take those images and push to docker hub
  - docker push manalikekre/multi-client
  - docker push manalikekre/multi-nginx
  - docker push manalikekre/multi-server
  - docker push manalikekre/multi-worker
